### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Kjm04175** [MP-TermProject/HwajilGuji#3]
![화질구지_middle](https://user-images.githubusercontent.com/30641096/79850486-fd21bd00-83fe-11ea-93eb-7615f4ffd436.jpg)
![화질구지](https://user-images.githubusercontent.com/30641096/79850510-04e16180-83ff-11ea-96e9-a21c2e571ae6.jpg)

**Comment by 201635848** [comment]
![](https://cdn.discordapp.com/attachments/694808960330367008/702102117552226335/63360faf5e30a271.jpg)
